### ISSUE TITLE
Language feature in recent Julia 0.7 

### ISSUE THREAD

**Issue by digital-carver** [adamslc/RequiredKeywords.jl#3]
Required keywords have been added (yay!) in to Julia 0.7 [as of Feb 2 2018](https://github.com/JuliaLang/julia/pull/25830). The README should probably mention this, and the macro should perhaps be a no-op for recent versions of Julia 0.7 (whatever the DEV build number for that change is) and above.

**Comment by adamslc** [comment]
Thanks for the heads up.

**Comment by stevengj** [comment]
See also #5.
